### ISSUE TITLE
blocking event should be killed by the VM

### ISSUE THREAD

**Issue by mbonani** [Mobsya/aseba-target-thymio2#51]
actually it seems that a blcoking event whit a while loop is not killed and block all the VM.

```
var a = 0

onevent button.center
	while a == 0 do
		call leds.top(0,255,0) # green
	end

onevent button.forward
	call leds.top(0,0,255) # blue
```
it is refered also here:
https://github.com/Mobsya/aseba/issues/653

**Comment by cor3ntin** [comment]
The vm will never exit the loop, so it will never process any incomming event or anything else.
The vm could put a limit on the number of instructions that can be run and abort when we go over.

As written the above code can never be supported, it's an infinite loop

**Comment by stephanemagnenat** [comment]
The original design was that infinite (or taking too long) loops will be killed if there are incoming events (either internal or from the network). If my memory is correct, the idea was to allocate 1k instructions upon an event that will surely be executed, but exceeding this number there is no guarantee (the 1k number is arbitrary of course, but it did sound reasonable for a small robot like Thymio). The behaviour of the simulator should be consistent with this design. I think that at some point the Thymio also followed that, but I am not totally sure we might have missed it all along (which seems strange, as for the paper for sure we had this behaviour).

**Comment by cor3ntin** [comment]
Reading at the code  more carefully, it doesn't seem much is missing 

https://github.com/Mobsya/aseba/blob/5b32558e4bd3cc7e58075bce548c1e7636308ac4/aseba/vm/vm.c#L532

**Comment by cor3ntin** [comment]
PR https://github.com/Mobsya/aseba/pull/666 
Thymio has a 1000 steps limit - that seems low, do we increase it @mbonani?

**Comment by mbonani** [comment]
I will make some test, probably it is not so low.

**Comment by mbonani** [comment]
clearly 1000 step are not sufficient:
a simple code that should work 
```
var buff[500]
var i
var j


onevent button.forward
	for i in 0:499 do
		buff[i]=i
	end
```
it is working with 10000 limit
 but no more with the following code
```
var buff[500]
var i
var j

onevent button.forward
for j in 0:1 do
	for i in 0:499 do
		buff[i]=i
	end
end
```
with 0xFFFF (Max)
`j` can go up to 10
and it makes go out from an infinite loop in less of 1 sec that's for me reasonable

**Comment by cor3ntin** [comment]
That was my gut feeling - do you want me to make a pr or will you ?

**Comment by mbonani** [comment]
I will do

**Comment by stephanemagnenat** [comment]
Just a note, as long as there is no incoming event, the current one is not killed. But I see the rationale. According to the [aseba paper](http://stephane.magnenat.net/publications/ASEBA,%20A%20Modular%20Architecture%20for%20Event-Based%20Control%20of%20Complex%20Robots%20-%20Magnenat%20et%20al.%20-%20IEEE%20TM%20-%202010.pdf) (p. 8), the VM executes 600k instructions per second. So if you put 30k as the minimal amount, it should have a delay than no more than 50ms in average. Note that you can also put an initial large amount, to make sure to execute at least these number of instructions, and then using a smaller amount, so that there is more reactivity. This requires a bit more complex glue code though.

**Comment by mbonani** [comment]
fix in v14
